### PR TITLE
Master improvements

### PR DESCRIPTION
**Pull request by dereuromark**
From 103 to 147 sniffs.
https://github.com/php-fig-rectified/psr2r-sniffer/pull/11/files#diff-2a41cc7e5c78e0388f176028f6472110

Please confirm/verify all good.

### CODE REVIEW

**Comment by gmponos** [comment]
A package like this I  don't believe that should require an external package like `spryker`. Maybe the other way around.

**Comment by dereuromark** [comment]
It doesn't, it only requires the sniffer packages from that and slevomat/coding-standard.
To avoid duplicating them and then fixing one without fixing the other (undry => errors).

**Comment by mrrsm** [comment]
Is there still a chance this is going to be merged?  I have been testing with this branch on some projects locally and things seem to be working.

**Comment by dereuromark** [comment]
I am still thinking about the dependencies. But then we can soon start to use it in master, yeah.

**Comment by dereuromark** [comment]
This requires now a new develop branch (without merge conflicts)
but then we can merge the main improvements

- phpunit modernized
- new/better sniffs?

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/php-fig-rectified/psr2r-sniffer/pull/19

**Pull request closed without merging**
